### ISSUE TITLE
Race Condition in ResourceBundleMessageResolver

### ISSUE THREAD

**Issue by vjkoskela** [sebthom/oval#10]
There is a second more subtle race condition in this class with version 1.87. The first was the concurrent  initialization of `messageBundlesByLocale` which was addressed by adding double check locking in https://github.com/sebthom/oval/commit/206ced8e96639f6f7e72a8bc1c661772628b9b46. 

The new issue is that the double check locking is not sufficient to ensure the contents of **both** `messageBundlesByLocale` (target of `synchronized`) and `messageBundleKeys` (not synchronized) are updated across threads. So while the double check locking prevents concurrent initialization, the contents of `messageBundleKeys` is not synchronized to other threads following population.

The simple solution would be to use Java's `ConcurrentHashMap` for both of these members: 

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html

However, it looks like the project is not using Java's collections or at least it supports using others as well via the `CollectionFactory` abstraction. 

There are two other options at least to ensure the data is updated across threads:

1) Ensure `synchronized` is used around all accesses to the two maps (`messageBundlesByLocale` and `messageBundleKeys`).
2) Wrap both the map instances in `Collections.synchronizedMap`.

Neither of these is particularly performant since they acquire locks on all accesses across the entire map. It's up to you of course, but as far as I can tell Trove has not been released since 2009 and Javolution since 2013. Is the abstraction across collection classes worth maintaining? 

In fact, looking at the `Map` implementations returned by the three `CollectionFactory` implementations it seems like the JDK and Javolution factories return linked hash maps while the Trove one returns a regular (non-linked) hash map. I could not find a definitive answer to this from the Trove docs, but did find this:

https://stackoverflow.com/questions/15048754/is-there-any-ordered-map-in-gnu-trove-library

This discrepancy could lead to other bugs. I only mention this as additional food for thought regarding the use of Java Collections versus the abstractions because again as far as I can tell neither Trove or Javolution support concurrent hash maps. Dropping Trove and Javolution would allow you to use `ConcurrentHashMap`.

Below is the stack trace for the `NullPointerException` we countered resulting from this race condition:

```
[ERROR] Tests run: 25, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.087 s <<< FAILURE! - in com.arpnetworking.commons.builder.OvalBuilderTest
[ERROR] testFailureMaxViolation(com.arpnetworking.commons.builder.OvalBuilderTest)  Time elapsed: 0.08 s  <<< ERROR!
java.lang.NullPointerException
	at net.sf.oval.localization.message.ResourceBundleMessageResolver.getMessage(ResourceBundleMessageResolver.java:87)
	at net.sf.oval.localization.message.ResourceBundleMessageResolver.getMessage(ResourceBundleMessageResolver.java:75)
	at net.sf.oval.internal.MessageRenderer.renderMessage(MessageRenderer.java:28)
	at net.sf.oval.Validator.renderMessage(Validator.java:1244)
	at net.sf.oval.Validator._checkConstraint(Validator.java:572)
	at net.sf.oval.Validator.checkConstraint(Validator.java:845)
	at net.sf.oval.Validator._validateObjectInvariants(Validator.java:602)
	at net.sf.oval.Validator.validateInvariants(Validator.java:1384)
	at net.sf.oval.Validator.validate(Validator.java:1308)
	at com.arpnetworking.commons.builder.OvalBuilder.validateWithReflection(OvalBuilder.java:263)
	at com.arpnetworking.commons.builder.OvalBuilder.build(OvalBuilder.java:165)
	at com.arpnetworking.commons.builder.OvalBuilderTest.testFailureMaxViolation(OvalBuilderTest.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   OvalBuilderTest.testFailureMaxViolation:160 » NullPointer
```

Finally, there is a third race condition in this class where `public boolean addMessageBundle(final ResourceBundle mb)` is invoked concurrently (same goes for `removeMessageBundle`). This could overwrite a partially initialized `List` inside `messageBundleKeys`. This is not an issue for us because we don't add message bundles in our implementation. However, it could be an issue for other clients.

Overall, in the longer term I would suggest reworking this class to be immutable after construction. You could use a builder or other construction technique to first populate and customize the resource bundles, and then create an immutable resource resolver for which it will be (more) trivial to ensure correct concurrent operation. 

I can submit a pull request for one of the short-term solutions if you like provided you can give some guidance about which direction you would like to go.

**Comment by sebthom** [comment]
Hi Ville, 
I will look into it. 

Thanks for the detailed analysis.

Regards,
Seb

**Comment by sebthom** [comment]
Hi Ville,
please give the latest snapshot a try http://oval.sourceforge.net/mvn-repo/snapshot/net/sf/oval/oval/1.88-SNAPSHOT/

Regards,
Seb

**Comment by vjkoskela** [comment]
Thanks Seb, I can see if it will break but I don't have a consistently reproducible test case because of the nature of the interaction with our application.

Looking at the changes you made I am concerned that the read path does not always go through the synchronization point (e.g. if `if (bundlesOfLocale == null)` is `false` -- line 135). Therefore, it is possible that a reader thread is not guaranteed to see an up to date view the members because that thread did not pass through a barrier.

Also, as a result of not fully synchronizing access it is possible to get a concurrent modification exception to the data structures if a read and a add or remove is performed at the same time by two different threads. This is another way to think of the same problem although this path is not directly affecting us at the moment (because we don't call add or remove).

**Comment by sebthom** [comment]
Hi Ville, 

an instance of `BundlesAndKeys` and it's contained collections are never modified once assigned to the `bundlesAndKeys` instance variable (they are replaced on update similar to CopyOnWriteArrayList). Thus any read access to them via the `bundlesAndKeys` instance variable will not result in concurrent modification exceptions.

The unsynchronized check `if (bundlesOfLocale == null) is false` in line 135 is done again within the synchronized block in line 138 (DLC).

Regards,
Seb

**Comment by vjkoskela** [comment]
I'm running my tests against `oval-1.88-20170910.120417-8` from your snapshot repository. I'll take another look at the code next week.

**Comment by vjkoskela** [comment]
After twelve hours of repeatedly running our test suite I am happy to report we have not run into any race conditions. However, these tests are by no means conclusive.

Looking at the changes I agree that add and remove now appear safe with the addition of the synchronized blocks. I am still concerned about the execution of `getMessage` under multiple threads; for example:

`bundlesOfLocale == null``
T1 - locks and initializes the reference
T2 - sees the reference is not null does not enter lock

As a consequence of not entering the lock there is no synchronization point for T2 with respect to the visibility or content consistency of either `bundlesOfLocale` or `keysOfBundles` (via `bundlesAndKeys`). Specifically, while the references to one or both `bundlesOfLocale` or `keysOfBundles` may be updated in the view of T2 (e.g. not `null`); what guarantees that their contents are up to date within the view of T2? The consistency of their contents may be a consequence of ordering, but I am not sure - my preference is to typically use concurrent data structures to ensure consistency of the data across threads.

Let me know when 1.88 is GA and we'll switchover to that and report any further issues should they arise.

**Comment by sebthom** [comment]
Hi Ville,

thanks for your update I will prepare a new release.

Regarding your concern, I think your observation is wrong. The unsynchronized code in [ResourceBundleMessageResolver#getMessage](https://github.com/sebthom/oval/blob/master/src/main/java/net/sf/oval/localization/message/ResourceBundleMessageResolver.java#L132) never performs a second operations on `this.bundlesAndKeys` with values it retrieved from it before because as you said between both calls the instance `BundlesAndKeys` may have been replaced.

Instead the code first keeps a reference to the current instance hold by `this.bundlesAndKeys` in a local `context` variable and performs subsequent operations only on that `context` variable - no matter if another thread assigns another instance to `this.bundlesAndKeys`.

I hope that addresses your concern.

Regards,
Seb

**Comment by sebthom** [comment]
Solved in https://bintray.com/sebthom/maven/oval/1.90
