### ISSUE TITLE
fully qualified JSR 303 annotations being ignored

### ISSUE THREAD

**Issue by mcgaw** [sebthom/oval#11]
Hi. I'm trying to use your library together with [Immutables](https://github.com/immutables/).

The Immutables generated classes fully qualify the annotations so that `@NotEmpty` becomes `java.lang.@NotEmpty`. (I'm using the JSR 303 annotations because the Immutables library does not copy across the native Oval versions, something to do with annotation types).

Oval is ignoring the annotation unless I remove the `java.lang.` prefix.

I'm using Java 8.

Thanks.

**Comment by sebthom** [comment]
Hi
can you please provide a small test case. 

Thanks,
Seb

**Comment by mcgaw** [comment]
Both of these [tests](https://github.com/mcgaw/oval-defect) should pass (I guess!). Cheers.

**Comment by mcgaw** [comment]
Did you manage to take a look at that? I'm going to have to take a look myself as the [bval](https://bval.apache.org/) lib seems to be exhibiting the same behaviour.

**Comment by sebthom** [comment]
Sorry, not yet, will do it over the weekend.

**Comment by mcgaw** [comment]
OK, cheers dude. It seems like it should be something simple.. famous last words.

**Comment by mcgaw** [comment]
Sorry, I've been an idiot. I was using 2.0 validation api annotations, which are not supported.

**Comment by sebthom** [comment]
FYI version 1.90 now also understands the new BV2.0 built-in constraints. https://bintray.com/sebthom/maven/oval/1.90
