### ISSUE TITLE
How do I create custom XML based constraints with the OVal validation

### ISSUE THREAD

**Issue by swaraich09** [sebthom/oval#125]
Hi ,

I am trying to create create custom annotation based constraints with the Oval validation framework ,
I am able to define all the constraints I want in the XML configuration file except for the custom constraint.

Annotation based I have the following code:

<img width="786" alt="Screen Shot 2021-08-04 at 12 08 07 PM" src="https://user-images.githubusercontent.com/88456964/128240590-fc46c9b7-0b51-4f74-ba7e-0544803fa7cf.png">

<img width="973" alt="Screen Shot 2021-08-04 at 12 08 40 PM" src="https://user-images.githubusercontent.com/88456964/128240661-bea71758-a360-4849-ada7-5cfdb01d8daa.png">

Above code works when used with code as annotation:
<img width="711" alt="Screen Shot 2021-08-04 at 12 13 41 PM" src="https://user-images.githubusercontent.com/88456964/128241170-fcc6b498-c91f-4db0-8b3c-da67beb71db8.png">

But When When used in xml as below:

        <field name="CountryID" overwrite="false">
            <notNull/>
            <com.mcd.dqplugin.constraint.CountryCodeValidation />
        </field>

It throws error as:
Exception in thread "main" com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.security.ForbiddenClassException

Please suggest correct way to define  custom constraint check (CountryCodeValidation) in my XML configuration.

**Comment by sebthom** [comment]
You need to specify a class and not an interface in XML. So I guess in your case `IDValidationConstraint` instead of `CountryCodeValidation`.

**Comment by swaraich09** [comment]
@sebthom : Thanks for replying. But i have tried with specifying class as well. It gives same error.

**Comment by sebthom** [comment]
Ah ok, as a security measure in the latest releases you need to tell XStream (the underlying XML serialization libary) which classes it can instantiate.

Try something like this:
```java
XStream myXStream = XMLConfigure.createXStream();
myXStream.allowTypesByWildcard(new String[] {"com.mcd.dqplugin.constraint.**"});
new Validator(new XMLConfigurer(myXStream));
```

**Comment by swaraich09** [comment]
I have tried as below:

XMLConfigurer xmlConfigurer = new XMLConfigurer(new File("src/main/resources/" + "oval-config.xml"));
        xmlConfigurer.getXStream().allowTypesByWildcard(new String[]{"com.mcd.dqplugin.constraint.**"});
        Validator validator = new Validator(xmlConfigurer);

**Comment by sebthom** [comment]
You whitelist your package too late. You need to configure xstream before the xml file is parsed. please try the way I outlined.

**Comment by swaraich09** [comment]
I tried as below :

            File file = new File(classLoader.getResource("oval-config.xml").getFile());
            XStream myXStream = XMLConfigurer.createXStream();
            myXStream.allowTypesByWildcard(new String[] {"com.mcd.dqplugin.constraint.**"});
            myXStream.fromXML(file);
            Validator validator =  new Validator(new XMLConfigurer(myXStream));

It ran fine without any errors but returned empty ConstraintViolation list.

**Comment by sebthom** [comment]
Try this:

```java
InputStream config = classLoader.getResourceAsStream("oval-config.xml");
XStream myXStream = XMLConfigurer.createXStream();
myXStream.allowTypesByWildcard(new String[] {"com.mcd.dqplugin.constraint.**"});
Validator validator = new Validator(new XMLConfigurer(myXStream, config));
```

**Comment by swaraich09** [comment]
Thanks @sebthom . This worked.
