### ISSUE TITLE
Support for importing oval xml in other oval xmls

### ISSUE THREAD

**Issue by TAMILSELVANP** [sebthom/oval#13]
we want define basic constraint sets in oval xmls and import them and use within multiple other oval xmls

**Comment by sebthom** [comment]
You can pass multiple xml configurers to an validator instamce, see https://github.com/sebthom/oval/blob/master/src/test/java/net/sf/oval/test/validator/XMLConfigurationTest.java#L68

**Comment by TAMILSELVANP** [comment]
I am looking for the option for importing XMLConfigurationTest.xml into XMLConfigurationTest.inc.xml and pass only one(XMLConfigurationTest.inc.xml) to the validator. 
Similar to <import resource="classpath*:/spring-config.xml" /> as in spring.
