### ISSUE TITLE
Could OValContext preserve _args, _returns and _this?

### ISSUE THREAD

**Issue by cnfn** [sebthom/oval#18]
If constraint violations occur in `@Pre` and `@Post` check, it will throw a [ConstraintsViolatedException](https://github.com/sebthom/oval/blob/master/src/main/java/net/sf/oval/exception/ConstraintsViolatedException.java#L21) exception. But [ConstraintViolation.invalidValue](https://github.com/sebthom/oval/blob/master/src/main/java/net/sf/oval/ConstraintViolation.java#L36) is always null([validateMethodPre](https://github.com/sebthom/oval/blob/master/src/main/java/net/sf/oval/guard/Guard.java#L1277), [validateMethodPost](https://github.com/sebthom/oval/blob/master/src/main/java/net/sf/oval/guard/Guard.java#L1219)). Then, we will never to know the invalid value is what.

We cannot to know who trigger the violation by a easy way, because the expression maybe include `_this`, `_args`, or `returns`. So we cannot to preverse the `invalidValue`.

But, if we preserve all the value like `_this`, `_args`, `returns` by [ConstraintViolation.context](https://github.com/sebthom/oval/blob/master/src/main/java/net/sf/oval/ConstraintViolation.java#L34), it should be help developers find and fix bugs.

Do you think so?

**Comment by sebthom** [comment]
`_this` is already accessible via `ConstraintViolation.getValidatedObject()`. 

I don't think exposing the return value in case of a constraint violation is a good idea because that defeats the whole purpose of preventing the computed return value being accessible when a validation error is detected.

**Comment by cnfn** [comment]
I'm new to DBC, could you explain why cannot access the return value? Thanks~
