### ISSUE TITLE
Add support for Java 8's type-annotations

### ISSUE THREAD

**Issue by mridang** [sebthom/oval#19]
Hi Seb, any chance you'll be adding support for Java 8's type annotations? It would be handy to do this: `List<@NonNull String>`

**Comment by mridang** [comment]
Yay! Thank you.

**Comment by mridang** [comment]
@sebthom When will this be released to Maven Central? 🙏

**Comment by sebthom** [comment]
Hi Mridang, I actually stopped using Maven Central directly. I switched to JCenter https://bintray.com/bintray/jcenter which includes everything from maven central and more (also it is Gradle/Android default). Do you really require it on Maven Central?

**Comment by mridang** [comment]
Nopes. Jcenter is fine. Thx Seb.
