### ISSUE TITLE
Performance: ReflectionUtils.getMethodRecursive cache

### ISSUE THREAD

**Issue by an-bel** [sebthom/oval#3]
In our performance investigation we've realized that ValidateWithMethodCheck.isSatisfied method is a CPU bottleneck.

simple implementation suggestion:
I supposed that's because Class.getDeclaredMethod(methodName, parameterTypes) is a pretty heavy call, I suggest an LRU cache with maximum size configurable via an environment variable. This cache would use a composite "Class, methodName, Class[] parameters".

Some relatively small value like 256 could be used as cache max size default to ensure small memory footprint effect by default.

fancier implementation suggestion:
allow external injection via ClassMethodResolver interface so that oval users like us could replace default implementation with custom one, for example with a cache like I've described above.

**Comment by sebthom** [comment]
Please give this a try http://oval.sourceforge.net/mvn-repo/snapshot/net/sf/oval/oval/1.87-SNAPSHOT/
