### ISSUE TITLE
Profiles inside annotation list are ignored

### ISSUE THREAD

**Issue by PavelCibulka** [sebthom/oval#36]
Validation on this annotation works with profile check:
`@ValidateWithMethod(methodName = "checkPhoneMandatory", parameterType = String.class,
                profiles = {"warning", "check"}, message = "net.sf.oval.constraint.NotNull.violated",
                ignoreIfNull = false)`

This doesn't work:
`@ValidateWithMethod.List(value = {
@ValidateWithMethod(methodName = "checkPhoneMandatory", parameterType = String.class,
                profiles = {"warning", "check"}, message = "net.sf.oval.constraint.NotNull.violated",
                ignoreIfNull = false)
})`

**Comment by PavelCibulka** [comment]
Problem is probably in net.sf.oval.Validator.checkConstraint line 755
if (!isAnyProfileEnabled(check.getProfiles(), profiles))

Suggested fix:
 if (!(check instanceof ConstraintsCheck) && !isAnyProfileEnabled(check.getProfiles(), profiles))

**Comment by sebthom** [comment]
Good catch. Thank you!
