### ISSUE TITLE
AssertURLCheck work incorrect

### ISSUE THREAD

**Issue by cjdxhjj** [sebthom/oval#37]
it use startwith to check if the schema is correct, 
`private boolean isURISchemeValid(final String url) {
      for (final URIScheme scheme : permittedURISchemes)
         if (url.startsWith(scheme.getScheme()))
            return true;
      return false;
   }`
my code is
`
<assertURL connect="false" errorCode="20014" message="url is not correct">
                <permittedURIScheme>http</permittedURIScheme>
                <permittedURIScheme>https</permittedURIScheme>
            </assertURL>
`
when i test with httpa://www.google.com it passed!

**Comment by cjdxhjj** [comment]
thanks.

**Comment by sebthom** [comment]
You are welcome. Thanks for reporting.
