### ISSUE TITLE
if a class field is a Custom class which i also need to check。 what to do ?

### ISSUE THREAD

**Issue by zhouwenmo** [sebthom/oval#39]
if a class field is a Custom class which i also need to check。
what to do ?

**Comment by sebthom** [comment]
You can annotate that field with `@AssertValid`, see [Declaring constraints for nested properties](https://github.com/sebthom/oval/blob/master/USERGUIDE.md#declaring-constraints-for-nested-properties)

**Comment by zhouwenmo** [comment]
thanks
