### ISSUE TITLE
Validation of elements in nested collections doesn't work

### ISSUE THREAD

**Issue by ArnaudRivero** [sebthom/oval#56]
Hi,

When nesting collections together (for instance, a `List<List<Integer>>`), validation doesn't work on the elements of the deepest collection. For instance, the following code doesn't throw any exception: 

```
  private static List<List<@Min(value = 0) Integer>> validateList(List<List<Integer>> input) {
    return input;
  }

  public static void main(String[] args) {
    List<Integer>       negativeList = Collections.singletonList(-4);
    List<List<Integer>> nestedNegativeList  = Collections.singletonList(negativeList);

    validateList(nestedNegativeList);
  }

```

**Comment by sebthom** [comment]
Hi Arnaud, 

you are right, that is currently not supported. As a workaround you can create a custom constraint to perform the validation, see https://github.com/sebthom/oval/blob/master/USERGUIDE.md#custom-constraint-annotations
