### ISSUE TITLE
is there any support for list object validate

### ISSUE THREAD

**Issue by cjdxhjj** [sebthom/oval#63]
i'm do validation with assertValid, i'm seek a soultion to config a list object validation, but i can only found notemplty, minSize, maxSize check, can provider an assertCollectionValid ?

**Comment by sebthom** [comment]
Hi @cjdxhjj ,

would you mind providing a code example of what you are trying to achieve?

**Comment by cjdxhjj** [comment]
yes, i do, for example,
![image](https://user-images.githubusercontent.com/5616997/83468339-0ea2be00-a4af-11ea-81de-cc839a719933.png)
here, in my service, i defined two method, one add one bo, and another add batch,
in my service validator, i config it as flowing

![image](https://user-images.githubusercontent.com/5616997/83468479-73f6af00-a4af-11ea-88f8-d5c9c641b0fd.png)

**Comment by cjdxhjj** [comment]
and my part of bo validation is here
![image](https://user-images.githubusercontent.com/5616997/83468534-9c7ea900-a4af-11ea-973f-11f640fffe09.png)

**Comment by cjdxhjj** [comment]
i wan;t to config the batch method as flowing
![image](https://user-images.githubusercontent.com/5616997/83468644-fda67c80-a4af-11ea-8412-acf4a0e5a08b.png)

**Comment by sebthom** [comment]
This should have worked out of the box.

Can you try:
```xml
      <assertValid>
         <appliesTo>
            <constraintTarget>CONTAINER</constraintTarget>
            <constraintTarget>VALUES</constraintTarget>
            <constraintTarget>RECURSIVE</constraintTarget>
         </appliesTo>
      </assertValid>
```

**Comment by cjdxhjj** [comment]
thanks very much,i would has a try later

**Comment by sebthom** [comment]
@cjdxhjj did it work?

**Comment by cjdxhjj** [comment]
yes, it works, thanks very much, my config is here

![image](https://user-images.githubusercontent.com/5616997/84215566-3f12d980-aaf9-11ea-905f-eaef0622b206.png)

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/84215615-6073c580-aaf9-11ea-8743-cc167a44bb54.png)

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/84215658-826d4800-aaf9-11ea-89aa-24936adc44f1.png)

**Comment by cjdxhjj** [comment]
i share my experience to help others.

**Comment by cjdxhjj** [comment]
because i use scala, List is not recognition by oval, so i changed to  Array, the class name of Array[T] is [T, but Class.forName failed, so i wraped it in a class to avoid specify the class name.
i have debug into the source code, i found
![image](https://user-images.githubusercontent.com/5616997/84215913-6ae28f00-aafa-11ea-86bb-6c955e65a064.png)

**Comment by cjdxhjj** [comment]
isContainerValue is false, so i can simple make first predict true to valid the array object, i coniged as flowing, and it works
<assertValid>
                <appliesTo>
                    <constraintTarget>VALUES</constraintTarget>
                </appliesTo>
            </assertValid>

**Comment by cjdxhjj** [comment]
yes, i do.
