### ISSUE TITLE
how to constraint specific methods based on some inner state

### ISSUE THREAD

**Issue by adrian-herscu** [sebthom/oval#64]
Perhaps this is something that should be better explained in the documentation.

Having an object field like:

    private final ThreadLocal<MyConnection> connection = new ThreadLocal<>();

with several methods such as:

    public void init(final MyConnection myConnection) {...}
    public void method1(...) {...}
    public void method2(...) {...}
    ...

I would like to declare a constraint so `methodX` would fail if called when `null == connection.get()`.

Also asked on 
https://stackoverflow.com/questions/62368585/using-oval-framework-how-to-constraint-a-threadlocal-variable

**Comment by sebthom** [comment]
Hi Adrian,
can you please give me a full example of what you are trying to achieve.
I am not fully understanding what you are trying to achieve.

**Comment by cjdxhjj** [comment]
you can add method preCheck

**Comment by adrian-herscu** [comment]
```
package tester;

import net.sf.oval.exception.*;
import net.sf.oval.guard.*;
import org.testng.annotations.*;

@Guarded
public class OvalSelfTests {
    public static final class MyObject {
        private boolean flag = true;

        public void set(final boolean newFlag) {
            flag = newFlag;
        }

        public boolean get() {
            return flag;
        }
    }

    // ISSUE if private or protected then validation fails
    // Error: could not access: flag; in class: OvalSelfTests]
    // [Near : {... !_this.flag ....}]
    public boolean flag = true;

    public final MyObject myObject = new MyObject();

    public void reset() {
        flag = false;
    }

    public void resetMyObject() {
        myObject.set(false);
    }

    // ISSUE: if there are multiple methods this has to be repeated...
    @Pre(expr = "!_this.flag", lang = "mvel")
    public void flip() {
        flag = !flag;
    }

    // ISSUE: if there are multiple methods this has to be repeated...
    @Pre(expr = "!_this.myObject.get()", lang = "mvel")
    public void flipMyObject() {
        myObject.set(!myObject.get());
    }

    @Test
    public void shouldReset() {
        reset();
        assert !flag;
    }

    @Test
    public void shouldResetMyObject() {
        resetMyObject();
        assert !myObject.get();
    }

    @Test
    public void shouldFlip() {
        reset();
        flip();
        assert flag;
    }

    @Test
    public void shouldFlipMyObject() {
        resetMyObject();
        flipMyObject();
        assert myObject.get();
    }

    @Test(expectedExceptions = ConstraintsViolatedException.class)
    public void shouldFailOnConstraintsViolation() {
        flip();
    }

    @Test(expectedExceptions = ConstraintsViolatedException.class)
    public void shouldFailOnConstraintsViolationForMyObject() {
        flipMyObject();
    }
}

```

**Comment by adrian-herscu** [comment]
Ok... advanced to this one:

```
@Guarded(checkInvariants = false)
@Slf4j
public class OvalSelfTests4 {
    @NotNull(target = "mvel:get()") // ISSUE fails here see below
    private final ThreadLocal<Object> container = new ThreadLocal<>();

    public void setObject(@NotNull final Object object) {
        container.set(object);
    }

    @PreValidateThis
    public void useObject() {
        log.debug(">>> {}", container.get().toString());
    }

    @Test
    public void shouldUseMyContainer() {
        setObject("my string");
        useObject();
    }

    @Test(expectedExceptions = ConstraintsViolatedException.class)
    public void shouldFailOnUsingWithoutSetting() {
        try {
            useObject();
        } catch (final Throwable t) {
            log.debug(">>>> {}", t.getMessage());
            throw t;
        }
    }
}
```

I am getting

```
Caused by: net.sf.oval.exception.ObjectGraphNavigatorNotAvailableException: Object graph navigator mvel is not available.
	at net.sf.oval.ogn.ObjectGraphNavigatorRegistry.getObjectGraphNavigator(ObjectGraphNavigatorRegistry.java:48)
	at net.sf.oval.Validator.checkConstraint(Validator.java:780)
	at net.sf.oval.Validator._validateObjectInvariants(Validator.java:597)
	... 38 more
```


I have 
```
    <dependency>
      <groupId>org.mvel</groupId>
      <artifactId>mvel2</artifactId>
      <version>2.4.8.Final</version>
    </dependency>
```

and also have a working test with

```
    @Pre(expr = "!_this.myObject.get()", lang = "mvel")
```

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/84988875-55faa100-b175-11ea-84d8-85913b0e7a94.png)
remove mvel, and test again

**Comment by sebthom** [comment]
You could use this:
```java
@Guarded(checkInvariants = false)
@Slf4j
public class OvalSelfTests4 {

    @AssertValid
    private final ThreadLocal<Object> container = new ThreadLocal<Object>() {
        @IsInvariant
        @NotNull
        public Object get() {
           return super.get();
        }
    };

    // ...
}
```

**Comment by adrian-herscu** [comment]
> ![image](https://user-images.githubusercontent.com/5616997/84988875-55faa100-b175-11ea-84d8-85913b0e7a94.png)
> remove mvel, and test again

for

    @Pre(expr = "!_this.myObject.get()", lang = "mvel")

I am getting
    ExpressionLanguageNotAvailableException: Expression language mvel is not available

**Comment by adrian-herscu** [comment]
> You could use this:
> 
> ```java
> @Guarded(checkInvariants = false)
> @Slf4j
> public class OvalSelfTests4 {
> 
>     @AssertValid
>     private final ThreadLocal<Object> container = new ThreadLocal<Object>() {
>         @IsInvariant
>         @NotNull
>         public Object get() {
>            return super.get();
>         }
>     };
> 
>     // ...
> }
> ```

For this case it seems reasonable... But there are classes which are `final` or their methods marked `final` -- so this approach might fail. Also this approach assumes that the container  object is built by  the `@Guarded` class which may not always be the case.

**Comment by cjdxhjj** [comment]
i',m using xml config, there is clean bo and inteface.

**Comment by cjdxhjj** [comment]
for example .
![image](https://user-images.githubusercontent.com/5616997/85013703-9cf98e00-b197-11ea-98b0-3ce9e53df141.png)
![image](https://user-images.githubusercontent.com/5616997/85013759-af73c780-b197-11ea-922f-9f2a5f7cbeaa.png)

**Comment by adrian-herscu** [comment]
> i',m using xml config, there is clean bo and inteface.

Too much "design patterns" might kill you :) Seriously!
"bo" I assume you meant to Business Object is something the just holds data perhaps doing some parsing and formatting on that data. Why the hell it needs an interface?? That XML file is just yet another place to keep the same code you otherwise would keep in an annotation...
And all this does not solve the basic issue which target referring to a method and not just to a public field.

**Comment by sebthom** [comment]
This works too:
```java
@Guarded(checkInvariants = false)
@Slf4j
public class OvalSelfTests4 {

   @Assert(expr = "_value.get() != null", lang = "mvel")
   private final ThreadLocal<Object> container = new ThreadLocal<>();

   @PreValidateThis
   public void useObject() {
      LOG.debug(">>> {}", container.get());
   }

   // ...
}
```
If you get `ExpressionLanguageNotAvailableException: Expression language mvel is not available`, ensure you added MVEL as a dependency to your project:
```xml
      <dependency>
         <groupId>org.mvel</groupId>
         <artifactId>mvel2</artifactId>
         <version>2.4.8.Final</version>
      </dependency>
```

**Comment by adrian-herscu** [comment]
Fine :)
How the expression for NotNull#target is evaluated?

**Comment by sebthom** [comment]
@adrian-herscu  like this: https://sebthom.github.io/oval/USERGUIDE.html#declaring-nested-property-constraints

**Comment by sebthom** [comment]
I guess this is solved. Please reopen or open another issue if required.
