### ISSUE TITLE
Support for validation of interfaces

### ISSUE THREAD

**Issue by mridang** [sebthom/oval#67]
Hi @sebthom We've been using this for a while and we've hit this issue where we aren't sure how interfaces should be validated. Sorry if I'm using the wrong place to ask this but I couldn't find this in the docs.

Assume that we have an interface called

```java
public interface Person {

  @Required
  String getName();

}
```

with the following two implementations:

```java
public class Author implements Person {

  public String getName() {
    return "John Doe";
  }
}

public class Singer implements Person {

  public String getName() {
    return null;
  }
}
```

What is the recommended way to validate both implementations without having to implement the same annotation on both the getters?

**Comment by sebthom** [comment]
Hi Mridang, 

this should actually work out of the box. There is a test case for this https://github.com/sebthom/oval/blob/master/src/test/java/net/sf/oval/test/validator/InheritanceTest.java

If you can provide a unit test reproducing the issue I'll have a look.

Regards,
Seb

**Comment by mridang** [comment]
Thanks so much Seb. I'll give this a shot and revert if needed. Much appreciated.

**Comment by mridang** [comment]
Hi @sebthom I got around to this and this test doesn't work: Just wondering if we're missing  something when it comes to validating the getters on the interface


```java
package net.sf.oval.test.validator;

import java.util.List;

import org.junit.Assert;
import org.junit.Test;

import net.sf.oval.ConstraintViolation;
import net.sf.oval.Validator;
import net.sf.oval.constraint.NotNull;

/**
 * @author Sebastian Thomschke
 */
public class InheritanceTest extends Assert {

    public interface IEntity {

        @NotNull(message = "NOT_NULL")
        public String getName();
    }

    public static class EntityImpl implements IEntity {

        private String name;

        /**
         * @return the name
         */
        @Override
        public String getName() {
            return name;
        }
    }

    @Test
    public void testInheritance() {
        final Validator validator = new Validator();

        final IEntity e = new EntityImpl();

        final List<ConstraintViolation> violations = validator.validate(e);
        assertEquals(violations.size(), 1);
        assertEquals(violations.get(0).getMessage(), "NOT_NULL");
    }
}
```

**Comment by sebthom** [comment]
@mridang please try the new release 3.0.0.

**Comment by sebthom** [comment]
Please reopen if it still doesn't work as expected.
