### ISSUE TITLE
Support the latest OGNL version

### ISSUE THREAD

**Issue by lukaszlenart** [sebthom/oval#8]
I'm working on hardening OGNL to reduce possible feature security vulnerabilities. One of those changes is to always needed an implementation of the `MemberAccess` interface.

The latest changes are [here](https://github.com/jkuhnert/ognl/commit/e30b2112979d1be7bed8073f1f47bffed6277fb2)https://github.com/jkuhnert/ognl/commit/e30b2112979d1be7bed8073f1f47bffed6277fb2 and you can test them with a version 3.2.2 of OGNL.

Another thing is a way to configure how OGNL is used with OVal, it would be good if I could add a custom `Configurer` to setup OGNL.

**Comment by sebthom** [comment]
I now upgraded the optional dependency to 3.1.14. Newer versions require Java 7.

Users are free to specify higher versions if they run on newer JDKs
