### ISSUE TITLE
Index of an invalid object within a list

### ISSUE THREAD

**Issue by gary-madden** [sebthom/oval#88]
Hi there,

Is there an equivalent of [getPropertyPath](https://docs.oracle.com/javaee/7/api/index.html?javax/validation/ConstraintViolation.html) in Oval? I'm trying to construct the property path of nested invalid objects so I can return some detailed error messages in an API I'm building.

I posted a more detailed question on stackoverflow: https://stackoverflow.com/questions/65018656/index-of-an-invalid-object-within-a-list. 

Thanks

**Comment by sebthom** [comment]
This is currently not possible. This [code part](https://github.com/sebthom/oval/blob/5cb5a75c0deef47a41aac712f9e7520131989cdf/src/main/java/net/sf/oval/Validator.java#L802) would need to be extended to keep track of the index.

**Comment by gary-madden** [comment]
Thanks @sebthom. I'll look at adding this functionality.

**Comment by gary-madden** [comment]
Hi @sebthom. I created this PR to try to solve the issue https://github.com/sebthom/oval/pull/90

**Comment by sebthom** [comment]
@gary-madden I pushed a commit that adds two new methods to `ConstraintViolation`: `getContextPath()` and `getContextPathAsString()`. Please check if that suits your needs.

**Comment by gary-madden** [comment]
Hey @sebthom. This works perfectly for my needs. Thanks!

**Comment by sebthom** [comment]
3.1.0 is released now.
